### ISSUE TITLE
hourly weather data via attributes

### ISSUE THREAD

**Issue by JanDetrez** [jdejaegh/irm-kmi-ha#11] opened 2024-03-11 09:02 UTC
Would it be possible to expose the hourly weather data via attributes? More specifically I'm interested to retrieve the rain in the upcoming hours to see if I will let out my mowing robot or not. 

The default weather integration does it like below. 
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/8522d91c-abf0-4fe0-8606-e2497c0b89eb)

I can retrieve the rain data for the coming hours like:
`{{ (state_attr(''weather.forecast_home'',''forecast'')[0].precipitation
      | float(0)  + state_attr(''weather.forecast_home'',''forecast'')[1].precipitation
      | float(0)  + state_attr(''weather.forecast_home'',''forecast'')[2].precipitation
      | float(0) )  < 5 }}`

I suppose you have the data because i see it in the lovelace, but I don't see any state attributes I could retrieve.
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/ba5d5623-06a7-405b-831d-442454c00dd2)

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/f7f25808-3999-4450-8563-439b1505eec3)

**Comment by jdejaegh** [comment] 2024-03-17 14:09
Hello @JanDetrez 

When setting up the integration (or go in Settings > Devices & services > KMI and then select 'Configure' if you already added it), you can select an option for 'Use the deprecated forecast attribute'.  If you set it to 'Use for hourly forecast' then you'll have something similar to your screenshot of `weather.forecast_home`.

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/62e813ae-d50e-4732-8025-ba04bab5b2c6)

With that setting, the state will include a forecast attribute for the upcoming hours.  `precipitation_probability` is a value in % and `precipitation` is in mm, just like in the KMI app.

![image](https://github.com/jdejaegh/irm-kmi-ha/assets/31966277/27cd4ec4-9be1-41fc-923b-abd69aaa1369)

As the feature is already there, I am closing this issue.  Feel free to comment if something is unclear

**Closed by jdejaegh** 2024-03-17 14:09 UTC

**Comment by JanDetrez** [comment] 2024-04-09 10:27
This worked, but it seemed to have reset itself after updating. I had to re-enable it. I'm not sure if this is expected behaviour, and if there is a way to make this permanent? Why deprecate some and why not have all attributes at all times? Thank you.

**Comment by jdejaegh** [comment] 2024-04-09 16:40
> This worked, but it seemed to have reset itself after updating. I had to re-enable it. I'm not sure if this is expected behaviour, and if there is a way to make this permanent? 

It should keep the configuration and not reset between updates.  Do you know from which version to which version you updated?  I'll try to reproduce and fix it in the future.

> Why deprecate some and why not have all attributes at all times?

Not sure to understand what your question relates to.  I assume it's about the `forecast` attribute.

Home Assistant deprecated this attribute in the past and deleted it in 2024.4.  I had to provide the `forecast` attribute in another way for it to still be available to you and the other users of this integration.  

Some background discussion about the attribute being removed: 

- https://community.home-assistant.io/t/petition-dont-delete-the-forecast-attribute/609298  
- https://community.home-assistant.io/t/update-from-using-weather-attributes-with-the-new-service-weather-get-forecasts/702736

Basically, Home Assistant want to move towards service call for weather forecast.  the [weather.get_forecasts](https://www.home-assistant.io/integrations/weather/#service-weatherget_forecasts) service call replaces the attribute.

> Would it also be possible to have the hourly and daily forecasts at the same time? Now I have to choose between either one of them.

It is not possible using the attribute.  That's one of the motivation for Home Assistant to move to a service call instead of an attribute. If you really want it, make a second zone a the same location and get another instance of the integration (not super efficient but well).

My advice would be to update your setup with service calls to [weather.get_forecasts](https://www.home-assistant.io/integrations/weather/#service-weatherget_forecasts).  It's currently supported by all weather integrations (this one included).  It allows you to get daily, twice daily and hourly data depending on the parameter and what the weather integration provides.  This integration provides the three types of forecasts so enjoy!

I know that some things are only possible using the attribute.  That's why I am keeping it a little bit longer.  However, in the long run, I'll move to a service call only; just like Home Assistant did with 2024.4.

> Btw it also seems "daily" is in the dropdown twice for me

Typo in the translation file, it will be fixed in the next release.  One of them is supposed to be 'twice daily'.  Thanks

> Btw, thanks to KMI I now have this pretty nice and most importantly accurate weather card :-)

Cool setup!  Thanks for the feedback and I hope this reply helps with your questions :)

**Comment by JanDetrez** [comment] 2024-04-10 11:08
Many thanks for the feedback. I had missed this bit on the service calls. I solved my request to both have daily and hourly detailed forecast by making two template sensor:

> template:
>   - trigger:
>       - platform: time_pattern
>         seconds: /10
>     action:
>       - service: weather.get_forecasts
>         data:
>           type: hourly
>         target:
>           entity_id: weather.home
>         response_variable: response
>     sensor:
>       - name: KMI Forecast hourly
>         unique_id: kmi_forecast_hourly
>         state: "{{ now().isoformat() }}"
>         attributes:
>           forecast: "{{ response['weather.home'].forecast }}"
>   - trigger:
>       - platform: time_pattern
>         seconds: /10
>     action:
>       - service: weather.get_forecasts
>         data:
>           type: daily
>         target:
>           entity_id: weather.home
>         response_variable: response
>     sensor:
>       - name: KMI Forecast daily
>         unique_id: kmi_forecast_daily
>         state: "{{ now().isoformat() }}"
>         attributes:
>           forecast: "{{ response['weather.home'].forecast }}"


I run into one issue now, it seems that for gust speed, when there is none, the variable is not present in the template sensor I created above. I'm not sure how to work my way around the errors that come from this.
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/8ed8c5e9-b434-469a-b734-fa4199a07de5)

If I try to convert to float, it will give an errror
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/38ebef1e-48ce-42d8-ba35-4aa809e8f81f)


Extracting it from day 5, which has gust winds forecasted is fine
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/ad3db407-ba33-4ec6-a6ab-65477cb6dd9f)

In the (deprecated) attribute you have it would say null/none and would by float conversion go to 0
![image](https://github.com/jdejaegh/irm-kmi-ha/assets/16916740/89e537b0-f962-4829-831f-dcef922a7636)

**Comment by jdejaegh** [comment] 2024-04-13 09:07
I see the issue.  

When you use the (deprecated) attribute, I am in full control of what I return there: the output generated by the integration is blindly returned to the user.  

When you use the forecast service, some [Home Assistant Core logic](https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py#L704) handles my output before sending it to the user.  Part of that logic is to remove the keys for which the value is `None` (to not clog up the output I guess).  There is no way for Home Assistant Core to know if the value is `None` because the integration does not implement that feature or because the `None` is meaningful (like, there is no wind gusts today).

For your template, try to go from this:

```
{{ states.sensor.kmi_forecast_daily.attributes.forecast[0].wind_gust_speed | float(0) }}
```

to something like this

```
{{ states.sensor.kmi_forecast_daily.attributes.forecast[0].wind_gust_speed | default | float(0) }}
```

The Jinja `default` filter is probably what your are looking for.  Check their short and self-explanatory doc about it, they have examples that helped me to figure out how to use it: https://jinja.palletsprojects.com/en/latest/templates/#jinja-filters.default

**Comment by JanDetrez** [comment] 2024-04-14 06:05
Great, that worked. Thanks a lot!
